### ISSUE TITLE
How is ${NPM_TOKEN} set in .npmrc?

### ISSUE THREAD

**Issue by samuelpearce** [oacore/about#372]
Instructions in README is unclear where to put generated Github token.

I've generated a token as the README instructs.
I've identified that the file is set in `.npmrc`

Is the token meant to replace the string `${NPM_TOKEN}`?
I tried setting an environment variable `NPM_TOKEN=MY_GH_KEY` but without success so temporarily, I have replaced the string but can the README be updated to reflect where the key should go to avoid accidentally committing this change?

**Comment by viktor-yakubiv** [comment]
Thank you for spotting this, I will update the README as we also moved from Yarn to NPM completely because of GitHub Package Registry.

I have my token set as raw string in my `.zshrc` in a way `export NPM_TOKEN=string`. NPM should smoothly pick up `.npmrc` and replace environment variables there. Yarn could not work with it.

The package registry and its privateness is another subject to discuss though.

**Comment by samuelpearce** [comment]
Ok, thanks. I can confirm what you suggest addresses the problem.

I tried this 
```
NPM_TOKEN=[my secret token]
yarn install
```

expecting yarn to pick up the variable but this wasn't successful. Maybe `export` is the key command which was missing.

I have created a [PR](https://github.com/oacore/next/pull/373) to add instructions based on what you have described
